server:
  port: 8081

spring:
  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/spring_test
    driver-class-name: org.postgresql.Driver


  flyway:
    sql-migration-prefix: V   # V(version)__description.sql V1__init.sql
    baseline-on-migrate: true

app:
  services:
    greeting:
      message: Hello!
